# Generated by Django 5.2.6 on 2025-09-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vulgar', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(max_length=150, unique=True)),
                ('familia', models.CharField(max_length=100)),
                ('en_peligro', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('tamano_m2', models.IntegerField()),
                ('presupuesto_anual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('animales', models.ManyToManyField(related_name='zoos', to='zoo.animal')),
            ],
        ),
    ]
